version: '2'

services:

  freeradius:
    build: . #use "/Radius" if you copy this to your main docker-compose-file!
    #image: philleconnect/radiusserver:latest
    container_name: radiusserver
    hostname: radiusserver
    depends_on:
      - ldap
    # Wait for the LDAP to be up and running:
    command: >
      /bin/bash -c "
        while ! nc -z ldap 389;
        do
          echo 'waiting for LDAP...';
          sleep 1;
        done;
        echo 'LDAP-Server found, starting now';
      "
    restart: always
    ports:
     - "1812:1812/udp"
     - "1813:1813"
     - "18120:18120"
    env_file:
     - ./settings.env
#    networks:
#      - philleconnect

networks:
    default:
        external:
            name: servercontainers_philleconnect
